name: Docker Build and Push

on:
    push:
        tags:
            - "v*"

jobs:
    build-and-push:
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Repository
              uses: actions/checkout@v2

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract tag name
              id: tag_name
              run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

            - name: Build Docker image
              run: |
                  TAG=${GITHUB_REF#refs/tags/}
                  docker build -t ghcr.io/${{ github.repository_owner }}/es2025-s17-hu-r2-backend:$TAG -t ghcr.io/es2025-s17-hu-r2-backend:latest .

            - name: Push Docker image
              run: |
                  TAG=${GITHUB_REF#refs/tags/}
                  echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
                  docker push ghcr.io/${{ github.repository_owner }}/es2025-s17-hu-r2-backend:$TAG
                  docker push ghcr.io/${{ github.repository_owner }}/es2025-s17-hu-r2-backend:latest
